repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        args: ["--application-directories", ".:src"]

  - repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
      - id: black
        args: ["-S"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
