version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"  # (last stable CPython version)

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
    configuration: docs/conf.py

formats: all
