name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install '.[tests]'
      - run: ./run.sh coverage-all

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
